[2025-03-17 20:59:41,028] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: weather_ingestion.load_data scheduled__2025-03-17T19:58:33.989201+00:00 [queued]>
[2025-03-17 20:59:41,036] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: weather_ingestion.load_data scheduled__2025-03-17T19:58:33.989201+00:00 [queued]>
[2025-03-17 20:59:41,036] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2025-03-17 20:59:41,036] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2025-03-17 20:59:41,036] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2025-03-17 20:59:41,045] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_data> on 2025-03-17 19:58:33.989201+00:00
[2025-03-17 20:59:41,049] {standard_task_runner.py:52} INFO - Started process 10247 to run task
[2025-03-17 20:59:41,055] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'weather_ingestion', 'load_data', 'scheduled__2025-03-17T19:58:33.989201+00:00', '--job-id', '325', '--raw', '--subdir', '/Users/yellow/Desktop/data_engineering/airflow_weather_01/dags/dag_weather.py', '--cfg-path', '/var/folders/7m/b2x3pxpj4h398t57k9hlv4gm0000gn/T/tmp5_y1yvvz', '--error-file', '/var/folders/7m/b2x3pxpj4h398t57k9hlv4gm0000gn/T/tmp3f0jdxet']
[2025-03-17 20:59:41,057] {standard_task_runner.py:77} INFO - Job 325: Subtask load_data
[2025-03-17 20:59:41,095] {logging_mixin.py:109} INFO - Running <TaskInstance: weather_ingestion.load_data scheduled__2025-03-17T19:58:33.989201+00:00 [running]> on host 147.0.168.192.in-addr.arpa
[2025-03-17 20:59:41,131] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=weather_ingestion
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2025-03-17T19:58:33.989201+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-03-17T19:58:33.989201+00:00
[2025-03-17 20:59:41,182] {__init__.py:149} INFO - package: mysql.connector.plugins
[2025-03-17 20:59:41,182] {__init__.py:150} INFO - plugin_name: caching_sha2_password
[2025-03-17 20:59:41,183] {__init__.py:154} INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLCachingSHA2PasswordAuthPlugin
[2025-03-17 20:59:41,195] {python.py:152} INFO - Done. Returned value was: None
[2025-03-17 20:59:41,203] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=weather_ingestion, task_id=load_data, execution_date=20250317T195833, start_date=20250317T195941, end_date=20250317T195941
[2025-03-17 20:59:41,248] {local_task_job.py:154} INFO - Task exited with return code 0
[2025-03-17 20:59:41,267] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
