[2025-03-17 21:17:21,579] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: weather_ingestion.load_data scheduled__2025-03-17T20:16:13.775806+00:00 [queued]>
[2025-03-17 21:17:21,586] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: weather_ingestion.load_data scheduled__2025-03-17T20:16:13.775806+00:00 [queued]>
[2025-03-17 21:17:21,586] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2025-03-17 21:17:21,586] {taskinstance.py:1242} INFO - Starting attempt 1 of 2
[2025-03-17 21:17:21,586] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2025-03-17 21:17:21,595] {taskinstance.py:1262} INFO - Executing <Task(PythonOperator): load_data> on 2025-03-17 20:16:13.775806+00:00
[2025-03-17 21:17:21,599] {standard_task_runner.py:52} INFO - Started process 18428 to run task
[2025-03-17 21:17:21,605] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'weather_ingestion', 'load_data', 'scheduled__2025-03-17T20:16:13.775806+00:00', '--job-id', '336', '--raw', '--subdir', '/Users/yellow/Desktop/data_engineering/airflow_weather_01/dags/dag_weather.py', '--cfg-path', '/var/folders/7m/b2x3pxpj4h398t57k9hlv4gm0000gn/T/tmphqpfnoz7', '--error-file', '/var/folders/7m/b2x3pxpj4h398t57k9hlv4gm0000gn/T/tmpmo3vv8y5']
[2025-03-17 21:17:21,607] {standard_task_runner.py:77} INFO - Job 336: Subtask load_data
[2025-03-17 21:17:21,647] {logging_mixin.py:109} INFO - Running <TaskInstance: weather_ingestion.load_data scheduled__2025-03-17T20:16:13.775806+00:00 [running]> on host 147.0.168.192.in-addr.arpa
[2025-03-17 21:17:21,687] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=weather_ingestion
AIRFLOW_CTX_TASK_ID=load_data
AIRFLOW_CTX_EXECUTION_DATE=2025-03-17T20:16:13.775806+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-03-17T20:16:13.775806+00:00
[2025-03-17 21:17:21,741] {__init__.py:149} INFO - package: mysql.connector.plugins
[2025-03-17 21:17:21,742] {__init__.py:150} INFO - plugin_name: caching_sha2_password
[2025-03-17 21:17:21,742] {__init__.py:154} INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLCachingSHA2PasswordAuthPlugin
[2025-03-17 21:17:21,755] {python.py:152} INFO - Done. Returned value was: None
[2025-03-17 21:17:21,762] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=weather_ingestion, task_id=load_data, execution_date=20250317T201613, start_date=20250317T201721, end_date=20250317T201721
[2025-03-17 21:17:21,794] {local_task_job.py:154} INFO - Task exited with return code 0
[2025-03-17 21:17:21,813] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
